spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coolance-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  session:
    store-type: redis
  redis:
    host: 192.168.126.142
#security:
#  basic:
#    enabled: false
coolance:
  security:
    social:
      filterProcessesUrl: /qqLogin
      qq:
        appId: 101583248
        appSecret: 810f050efd1cb4a5079fd9ca194ff831
      weChat:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
#        providerId: callback.do
#      filter-processes-url: /qqLogin
    browser:
      signUpUrl: /demo-signUp.html
      signOutUrl: /coolance-logout.html
    oauth2:
      clients[0].clientId: coolapp
      clients[0].clientSecret: coolsecret
      clients[0].accessTokenValidateSeconds: 3600

      clients[1].clientId: test
      clients[1].clientSecret: test

#    browser:
#      loginPage: /demo-signIn.html
#      loginResponseType: REDIRECT
#    code:
#      image:
#        length: 6
#        width: 100
#        url: /user/*
server:
  port: 8080
  session:
    timeout: 600 #秒

#security:
#  oauth2:
#    client:
#      clientId: coolapp
#      clientSecret: coolsecret
