spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coolance-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  session:
    store-type: none
#security:
#  basic:
#    enabled: false
coolance:
  security:
    social:
      qq:
        appId: 101583248
        appSecret: 810f050efd1cb4a5079fd9ca194ff831
#        providerId: callback.do
#      filter-processes-url: /qqLogin
    browser:
      signUpUrl: /demo-signUp.html

server:
  port: 80
#    browser:
#      loginPage: /demo-signIn.html
#      loginResponseType: REDIRECT
#    code:
#      image:
#        length: 6
#        width: 100
#        url: /user/*