spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coolance-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  session:
    store-type: none
#security:
#  basic:
#    enabled: false
#coolance:
#  security:
#    browser:
#      loginPage: /demo-signIn.html
#      loginResponseType: REDIRECT
#    code:
#      image:
#        length: 6
#        width: 100
#        url: /user/*