spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coolance-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    #连接池及重试配置，防止mysql如果8小时自动断开连接问题
    max-active: 100
    min-idle: 10
    min-evictable-idle-time-millis: 1800000
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    validation-query: select 1
  session:
    store-type: none
#  redis:
#    host: 192.168.126.143
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      naming:
      #数据库表和字段命名策略
        implicit-strategy: com.coolance.security.rbac.repository.support.CoolanceImplicitNamingStrategy

#security:
#  basic:
#    enabled: false
coolance:
  security:
    social:
      filterProcessesUrl: /qqLogin
      qq:
        appId: 101583248
        appSecret: 810f050efd1cb4a5079fd9ca194ff831
      weChat:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
#        providerId: callback.do
#      filter-processes-url: /qqLogin
    browser:
      signUpUrl: /demo-signUp.html
      signOutUrl: /demo-logout.html
      loginResponseType: REDIRECT
      signInSuccessUrl: /manage.html
    oauth2:
      clients[0].clientId: coolapp
      clients[0].clientSecret: coolsecret
      clients[0].accessTokenValidateSeconds: 3600

      clients[1].clientId: test
      clients[1].clientSecret: test

#    code:
#      image:
#        length: 6
#        width: 100
#        url: /user/*
server:
  port: 8080
  session:
    timeout: 600 #秒

#security:
#  oauth2:
#    client:
#      clientId: coolapp
#      clientSecret: coolsecret
